"""Create initial structure

Revision ID: f38ab0a97fd1
Revises:
Create Date: 2024-08-04 19:54:01.478087

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f38ab0a97fd1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )

    op.create_table(
        "routine",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "periodicy", postgresql.ENUM("DAILY", "WEEKLY", "MONTHLY", "YEARKY", name="periodicyenum"), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["id_user"], ["user.id"], name=op.f("fk_routine_id_user_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine")),
    )
    op.create_index(op.f("ix_routine_id_user"), "routine", ["id_user"], unique=False)

    op.create_table(
        "frequency",
        sa.Column("id_routine", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["id_routine"], ["routine.id"], name=op.f("fk_frequency_id_routine_routine")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frequency")),
    )
    op.create_index(op.f("ix_frequency_id_routine"), "frequency", ["id_routine"], unique=False)

    op.create_table(
        "tracker",
        sa.Column("id_routine", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["id_routine"], ["routine.id"], name=op.f("fk_tracker_id_routine_routine")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracker")),
    )
    op.create_index(op.f("ix_tracker_id_routine"), "tracker", ["id_routine"], unique=False)

    op.create_table(
        "historic",
        sa.Column("id_routine", sa.BigInteger(), nullable=False),
        sa.Column("id_tracker", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["id_routine"], ["routine.id"], name=op.f("fk_historic_id_routine_routine")),
        sa.ForeignKeyConstraint(["id_tracker"], ["tracker.id"], name=op.f("fk_historic_id_tracker_tracker")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historic")),
    )
    op.create_index(op.f("ix_historic_id_routine"), "historic", ["id_routine"], unique=False)
    op.create_index(op.f("ix_historic_id_tracker"), "historic", ["id_tracker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historic_id_tracker"), table_name="historic")
    op.drop_index(op.f("ix_historic_id_routine"), table_name="historic")
    op.drop_table("historic")
    op.drop_index(op.f("ix_tracker_id_routine"), table_name="tracker")
    op.drop_table("tracker")
    op.drop_index(op.f("ix_frequency_id_routine"), table_name="frequency")
    op.drop_table("frequency")
    op.drop_index(op.f("ix_routine_id_user"), table_name="routine")
    op.drop_table("routine")
    op.drop_table("user")
    # ### end Alembic commands ###
