FROM python:3.11.1-slim

WORKDIR /app

RUN pip install -U pip &&\
    pip install poetry &&\
    poetry config virtualenvs.create false

RUN apt-get update -qq &&\
    apt-get install git build-essential libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -qq

ADD . .

RUN poetry install

EXPOSE 8000

ENTRYPOINT ["uvicorn", "src.routine_tracker_core.external_interfaces.routine_tracker_api.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]